---
- src: git@github.com:PopovNA91/elastic-role.git
  scm: git
  version: "2.0.0"
  name: elastic-role
- src: git@github.com:PopovNA91/kibana-role.git
  scm: git
  version: "2.0.0"
  name: kibana-role
- src: git@github.com:PopovNA91/filebeat-role.git
  scm: git
  version: "2.0.0"
  name: filebeat-role
